services:
  # =========================
  # VPN (uniquement pour qBittorrent)
  # =========================
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges:true

    environment:
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=wireguard

      - WIREGUARD_PRIVATE_KEY=${AIRVPN_PRIVATE_KEY}
      - WIREGUARD_PRESHARED_KEY=${AIRVPN_PRESHARED_KEY}
      - WIREGUARD_ADDRESSES=${AIRVPN_ADDRESS}

      # AirVPN endpoint générique
      - SERVER_REGIONS=Europe

      # port torrent
      - FIREWALL_VPN_INPUT_PORTS=10032
      - FIREWALL_INPUT_PORTS=10032

      # performances
      - DOT=off
      - DNS_ADDRESS=1.1.1.1
      - MTU=1320

      - TZ=Europe/Paris

    volumes:
      - ./config/gluetun:/gluetun

    ports:
      - 8080:8080
      - 10032:10032
      - 10032:10032/udp

    restart: unless-stopped
    networks:
      - media-net

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - WEBUI_PORT=8080
    volumes:
      - ./config/qbittorrent:/config
      - /mnt/medias/torrents:/downloads
    restart: unless-stopped

  # =========================
  # Indexers (hors VPN pour éviter Cloudflare)
  # =========================
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    networks:
      - media-net
    depends_on:
      - flaresolverr
    ports:
      - 9696:9696
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./config/prowlarr:/config
      - ./config/prowlarr/Definitions/Custom:/config/Definitions/Custom:ro
    dns:
      - 1.1.1.1
      - 1.0.0.1
    restart: unless-stopped

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    networks:
      - media-net
    expose:
      - "8191"
    security_opt:
      - no-new-privileges:true
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Paris
    dns:
      - 1.1.1.1
      - 1.0.0.1
    restart: unless-stopped

  # =========================
  # Arr stack (LAN normal)
  # =========================
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - media-net
    ports:
      - 8989:8989
    depends_on:
      - prowlarr
      - qbittorrent
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./config/sonarr:/config
      - /mnt/medias/torrents:/downloads
      - /mnt/medias/Medias/Series:/series
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      - media-net
    ports:
      - 7878:7878
    depends_on:
      - prowlarr
      - qbittorrent
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./config/radarr:/config
      - /mnt/medias/torrents:/downloads
      - /mnt/medias/Medias/Movies:/movies
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    networks:
      - media-net
    ports:
      - 6767:6767
    depends_on:
      - sonarr
      - radarr
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./config/bazarr:/config
      - /mnt/medias/Medias/Movies:/movies
      - /mnt/medias/Medias/Series:/series
    restart: unless-stopped

  # =========================
  # Front / media
  # =========================
  jellyseerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: jellyseerr
    networks:
      - media-net
    ports:
      - 5055:5055
    depends_on:
      - sonarr
      - radarr
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Paris
    volumes:
      - ./config/jellyseerr:/app/config
    user: "1000:1000"
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    networks:
      - media-net
    ports:
      - 8096:8096
      - 7359:7359/udp
      - 1900:1900/udp
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./config/jellyfin:/config
      - ./cache/jellyfin:/cache
      - /mnt/medias/Medias/Movies:/movies
      - /mnt/medias/Medias/Series:/series
    depends_on:
      - sonarr
      - radarr
    restart: unless-stopped

  # =========================
  # Tools
  # =========================
  autobrr:
    image: ghcr.io/autobrr/autobrr:latest
    container_name: autobrr
    networks:
      - media-net
    ports:
      - 7474:7474
    depends_on:
      - sonarr
      - radarr
      - qbittorrent
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./config/autobrr:/config
    restart: unless-stopped

  watcharr:
    image: ghcr.io/sbondco/watcharr:latest
    container_name: watcharr
    networks:
      - media-net
    ports:
      - 3080:3080
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Paris
    volumes:
      - ./config/watcharr:/data
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    networks:
      - media-net
    ports:
      - 9443:9443
      - 9000:9000
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/portainer:/data
    restart: unless-stopped

  glances:
    image: nicolargo/glances:latest
    container_name: glances
    pid: "host"
    networks:
      - media-net
    ports:
      - 61208:61208
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=Europe/Paris
      - GLANCES_OPT=-w
    restart: unless-stopped

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    networks:
      - media-net
    ports:
      - 9999:8080
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    networks:
      - media-net
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Paris
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REMOVE_VOLUMES=false
      - WATCHTOWER_POLL_INTERVAL=86400
    restart: unless-stopped
  
  # =========================
  # Nextcloud
  # =========================
  
  nextcloud:
    image: nextcloud:29
    container_name: nextcloud
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    ports:
      - 8088:80
    environment:
      - TZ=Europe/Paris
      - REDIS_HOST=nextcloud-redis
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=ncpassword
    volumes:
      - ./nextcloud/app:/var/www/html
      - ./nextcloud/data:/var/www/html/data
      - /mnt/medias/Medias:/var/www/html/data/thomas/files/Medias:ro
      - /mnt/medias/Shares/Nextcloud:/var/www/html/data/shares:ro
    networks:
      - media-net
    restart: unless-stopped

  nextcloud-db:
    image: mariadb:10.11
    container_name: nextcloud-db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=ncpassword
    volumes:
      - ./nextcloud/db:/var/lib/mysql
    networks:
      - media-net
    restart: unless-stopped

  nextcloud-redis:
    image: redis:7-alpine
    container_name: nextcloud-redis
    volumes:
      - ./nextcloud/redis:/data
    networks:
      - media-net
    restart: unless-stopped

networks:
  media-net:
    driver: bridge
